# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: test

on: [push]

permissions:
  pull-requests: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test with pytest
      run: |
        pytest --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=src | tee pytest-coverage.txt

    - name: Pytest coverage comment
      if: ${{ github.ref == 'refs/heads/master' }}
      id: coverageComment
      uses: MishaKav/pytest-coverage-comment@main
      with:
        hide-comment: true
        hide-report: true
        default-branch: master
        pytest-coverage-path: ./pytest-coverage.txt

    - name: Update Readme with Coverage Html
      if: ${{ github.ref == 'refs/heads/master' }}
      run: |
        sed -i '/<!-- Pytest Coverage Comment:Begin -->/,/<!-- Pytest Coverage Comment:End -->/c\<!-- Pytest Coverage Comment:Begin -->\n\${{ steps.coverageComment.outputs.coverageHtml }}\n<!-- Pytest Coverage Comment:End -->' ./README.md

    - name: Commit & Push changes to Readme
      if: ${{ github.ref == 'refs/heads/master' }}
      uses: actions-js/push@master
      with:
        branch: master
        message: Update coverage on Readme
        github_token: ${{ secrets.GITHUB_TOKEN }}
